- infrastructure/base/infra-metallb/infra-metallb.yaml
Reverts Truxnell/home-cluster#192
> Revert "chore(deps): update container image metallb/speaker to v0.10.2"

- infrastructure/base/infra-metallb/infra-metallb.yaml
Reverts Truxnell/home-cluster#191
> Revert "chore(deps): update container image metallb/controller to v0.10.2"

- infrastructure/base/infra-metallb/infra-metallb.yaml
Reverts Truxnell/home-cluster#194
> Revert "chore(deps): update helm release metallb to v2.4.2"

- apps/base/downloads/nzbget/nzbget.yaml
Reverts Truxnell/home-cluster#212
> Revert "chore(deps): update helm release nzbget to v11"

- apps/base/downloads/qbittorrent/qbittorrent.yaml
Reverts Truxnell/home-cluster#209
> Revert "chore(deps): update helm release qbittorrent to v11"

- apps/base/media/dizquetv/dizquetv.yaml
Reverts Truxnell/home-cluster#210
> Revert "chore(deps): update helm release dizquetv to v3"

- apps/base/organisers/sonarr/sonarr.yaml
Reverts Truxnell/home-cluster#204
> Revert "chore(deps): update helm release sonarr to v12"

- apps/base/organisers/readarr/readarr.yaml
Reverts Truxnell/home-cluster#203
> Revert "chore(deps): update helm release readarr to v5"

- apps/base/organisers/prowlarr/prowlarr.yaml
Reverts Truxnell/home-cluster#201
> Revert "chore(deps): update helm release prowlarr to v3"

- apps/base/organisers/lidarr/lidarr.yaml
Reverts Truxnell/home-cluster#200
> Revert "chore(deps): update helm release lidarr to v10"

- apps/base/home/homeassistant/homeassistant.yaml
Reverts Truxnell/home-cluster#199
> Revert "chore(deps): update helm release home-assistant to v9"

- apps/base/media/plex/plex.yaml
Reverts Truxnell/home-cluster#196
> Revert "chore(deps): update helm release plex to v5"

- infrastructure/base/infra-traefik/005-deployment.yaml
Reverts Truxnell/home-cluster#269
> Revert "chore(deps): update container image traefik to v2.5"

- apps/base/home/homeassistant/homeassistant.yaml
Reverts Truxnell/home-cluster#331
> Revert "chore(deps): update helm release home-assistant to v11"

- k8s/clusters/hegira/flux/vars/cluster-secrets.sops.yaml
- k8s/manifests/organizarrs/trash-updater/cronjob.yaml
- k8s/manifests/organizarrs/trash-updater/kustomization.yaml
- k8s/manifests/organizarrs/trash-updater/secret.sops.yaml
> refactor to use secret vars

- k8s/manifests/services/minio/helmrelease.yaml
Reverts Truxnell/home-cluster#903
Having issues with access denied
> Revert "feat(container): update docker image quay.io/minio/minio to release.2022-04-01t03-41-39z.fips"

- k8s/manifests/network-system/metallb/helmrelease.yaml
Reverts Truxnell/home-cluster#1028
> Revert "feat(helm)!: Update Helm chart metallb to 3.0.0"

- k8s/manifests/user/system-monitoring/blackbox-exporter/helmrelease.yaml
Reverts Truxnell/home-cluster#1122
> Revert ":arrow_up: feat(helm): Update Helm chart prometheus-blackbox-exporter to 5.8.0"

- k8s/manifests/user/organizarrs/calibre/helmrelease.yaml
Reverts Truxnell/home-cluster#1078
> Revert ":arrow_up: feat(helm): Update Helm chart calibre to 5.3.1"

- k8s/manifests/user/kube-system/descheduler/helmrelease.yaml
Reverts Truxnell/home-cluster#1236
> Revert ":arrow_up: feat(helm): Update Helm chart descheduler to 0.24.0"

- k8s/manifests/user/databases/postgresql/helmrelease.yaml
Reverts Truxnell/home-cluster#1273
> Revert ":arrow_up: fix(helm): Update Helm chart postgresql to 11.5.2"

- k8s/manifests/core/system-monitoring/grafana/helmrelease.yaml
Reverts Truxnell/home-cluster#1342
> Revert ":arrow_up: fix(helm): update Helm chart grafana to 6.30.3"

- k8s/manifests/user/vpn/downloads-gateway/helmrelease.yaml
Reverts Truxnell/home-cluster#1472
> Revert ":arrow_up: feat(helm): Update Helm chart pod-gateway to 5.6.2"

- k8s/manifests/user/vpn/downloads-gateway/helmrelease.yaml
Reverts Truxnell/home-cluster#1501
> Revert "Revert ":arrow_up: feat(helm): Update Helm chart pod-gateway to 5.6.2""

- k8s/manifests/user/services/paperless/helmrelease.yaml
Reverts Truxnell/home-cluster#1470
> Revert ":arrow_up: feat(helm): Update Helm chart paperless to 9.1.3"

- k8s/manifests/user/kube-system/reloader/helmrelease.yaml
Reverts Truxnell/home-cluster#1672
> Revert ":arrow_up: fix(helm): Update Helm chart reloader to v0.0.119"

- k8s/manifests/user/kube-system/reloader/helmrelease.yaml
Reverts Truxnell/home-cluster#1714
> Revert ":arrow_up: fix(helm): Update Helm chart reloader to v0.0.120"

- k8s/manifests/core/system-monitoring/vector/agent/helmrelease.yaml
- k8s/manifests/core/system-monitoring/vector/aggregator/helmrelease.yaml
Reverts Truxnell/home-cluster#1781
> Revert ":arrow_up: fix(helm): Update Helm chart vector to 0.16.2"

- k8s/manifests/user/home-automation/emqx/helmrelease.yaml
Reverts Truxnell/home-cluster#2095
> Revert ":arrow_up: fix(helm): Update Helm chart emqx to 5.0.14"

- kubernetes/apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml
- kubernetes/apps/rook-ceph/rook-ceph/operator/helmrelease.yaml
Reverts truxnell/home-cluster#2291
> Revert ":arrow_up: feat(helm): Update rook-ceph-suite group to v1.11.0 (minor)"

- kubernetes/apps/volsync/volsync/app/helmrelease.yaml
Reverts truxnell/home-cluster#2278
> Revert ":arrow_up: feat(helm): Update chart volsync to 0.6.0"

- kubernetes/apps/services/vikunja/app/helmrelease.yaml
Reverts truxnell/home-cluster#2347
> Revert ":arrow_up: fix(container): Update image vikunja/api to v0.20.4"

- kubernetes/apps/monitoring/snmp-exporter-vyos/app/helmrelease.yaml
Reverts truxnell/home-cluster#2455
> Revert "feat(helm-chart): update helm release prometheus-snmp-exporter to 1.4.0"

- kubernetes/apps/services/vikunja/app/helmrelease.yaml
Reverts truxnell/home-cluster#2478
> Revert "fix(docker-image): update vikunja/api docker tag to v0.20.4"

- kubernetes/apps/monitoring/kube-prometheus-stack/app/helmrelease.yaml
Reverts truxnell/home-cluster#2662
> Revert "fix(helm-chart): update helm release kube-prometheus-stack to 45.28.1"

- kubernetes/apps/organizarrs/lidarr/app/helmrelease.yaml
Reverts truxnell/home-cluster#2857
> Revert "feat(docker-image): update youegraillot/lidarr-on-steroids docker tag to v1.3.0"

- kubernetes/helios/apps/default/qbittorrent/app/helmrelease.yaml
- kubernetes/helios/apps/default/qbittorrent/lidarr/helmrelease.yaml
- kubernetes/helios/apps/default/qbittorrent/readarr/helmrelease.yaml
Reverts truxnell/home-cluster#3237
> Revert "feat(docker-image): update ghcr.io/onedr0p/qbittorrent docker tag to v4.6.0"

- kubernetes/apps/downloads/autobrr/app/helmrelease.yaml
Reverts truxnell/home-cluster#3426
> Revert "feat(docker-image): update ghcr.io/autobrr/autobrr docker tag to v1.34.1"

- kubernetes/apps/services/immich/app/machine-learning/helmrelease.yaml
- kubernetes/apps/services/immich/app/microservices/helmrelease.yaml
- kubernetes/apps/services/immich/app/server/helmrelease.yaml
Reverts truxnell/home-cluster#3462
> Revert "feat(docker-image): update immich group to v1.91.3 (minor)"

- kubernetes/apps/services/immich/app/machine-learning/helmrelease.yaml
- kubernetes/apps/services/immich/app/microservices/helmrelease.yaml
- kubernetes/apps/services/immich/app/server/helmrelease.yaml
Reverts truxnell/home-cluster#3599
> Revert "feat(docker-image): update immich group to v1.92.1 (minor)"

- kubernetes/apps/vpn/downloads-gateway/app/helmrelease.yaml
Hi, thanks for the repo. Getting inspiration from it, I found that gluetun does not pick up new version. Looked through common library, there's missing key.
> fix: fix indentation for gluetun to use correct image
